### ISSUE TITLE
⌘+Enter should invoke send action

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/MessageViewController#1]
Have to manually invoke a send action now. Can’t use an external keyboard’s ⌘+Enter.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Should be easy to copy over from Slacks control. Wanna take it on?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
