### ISSUE TITLE
Attributed text highlight needs to retain paragraph style

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/MessageViewController#25]
Noticeable when the first text is a mention in GitHawk. Tapping backspace changes the height.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
I see it, the slight flutter with a few pixels height difference that makes the bar "bounce" ?

**Comment by rnystrom** [comment]
@nathantannar4 exactly!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
