### ISSUE TITLE
Height skips around when going from empty to first char

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/MessageViewController#26]
Notice some slight jumping. Wonder if we need to min to the line height of the font?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Did that fix it?

**Comment by rnystrom** [comment]
Oops reminds me I need to update the message VC pod before we ship. Will do.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
