### ISSUE TITLE
Highlight everything after setting text to empty then inserting

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/MessageViewController#31]
We need to clear the attributes.

- Open an Issue in GitHawk
- Select an autocomplete as first word and keep typing
- airplane mode
- Hit send

![GitHawk Upload by rnystrom](https://i.imgur.com/MEA0UZf.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
In GitHawk is the text being reset via the cache property in the `MessageViewController` when the network request failed? I see thats using just a `String` and not an `NSAttributedString`

**Comment by rnystrom** [comment]
It’s just setting the string. My hunch is that the first character’s attributes still exist in the text view and are applied to everything...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Fixed in #59
