### ISSUE TITLE
support for iOS 9

### ISSUE THREAD

**Issue by bensonyang2015** [GitHawkApp/MessageViewController#36]
I've locally changed settings to support iOS 9 and it works perfectly.
Would you do that to officially support iOS 9?

**Comment by BasThomas** [comment]
Feel free to open a pull request 😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I'd be happy to review a PR!

**Comment by Fogh** [comment]
I have created a pull request for this. Only the podspec needs to be updated. #40
