### ISSUE TITLE
messageView.font seems to not be working?

### ISSUE THREAD

**Issue by siefix** [GitHawkApp/MessageViewController#73]
I keep trying to set the font on my messageView just like in the examples

`messageView.font = .systemFont(ofSize: 15)`
or 
`messageView.font = .systemFont(ofSize: 20)`
or whatever

and it always seems to start going back to [I think] size 17 font.

Screenshot below shows size 20 font for the first word then for some reason gets smaller and stays like that.

Realize I'm using a custom keyboard: Tried it with both default iOS keyboard and Gboard.

![img_5202](https://user-images.githubusercontent.com/20218698/44867909-cc4fab80-ac4e-11e8-97fc-cd6a8b6bbdda.jpg)

**Comment by rnystrom** [comment]
When do you set the font?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by siefix** [comment]
The font I want will only be the first word (or sometimes first letter) then will revert to size 17 for everything else. (example in the picture above, I wanted size 20, but after first word it reverted to size 17)

**Comment by rnystrom** [comment]
I mean do you set it in `viewDidLoad` or something? Also which version of the lib are you using? Does the big repro if you update to the latest or just use `master`? I swear I hit this bug and fixed it for GitHawk but can’t recall.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by siefix** [comment]
Yes I set it in viewDidLoad like the Example.

But looks like it was the file version.

Was using `pod 'MessageViewController'` as shown in the README but was probably giving me the 0.2.1 version from March

updated to `pod 'MessageViewController', :git =>  'https://github.com/GitHawkApp/MessageViewController.git'`

And it solved the change in font size.

But opened up some new problems which I'll open new issues for.

Thanks for taking the time btw.
