### ISSUE TITLE
26 error on Swift 4.2 on Xcode 10

### ISSUE THREAD

**Issue by ashishfission** [GitHawkApp/MessageViewController#85]
Xcode : 10
iOS : 12
Swift 4.2

While integrating MessageViewController via Cocoapods, I am getting lots of error. PFA
![screenshot 2018-12-05 at 11 33 43 am](https://user-images.githubusercontent.com/1861018/49493345-cd156080-f881-11e8-8690-503b12ec6626.png)

**Comment by SD10** [comment]
Hey @ashishfission, this project supports Swift 4.0. 

You'll need to add a CocoaPods post-install hook to your Podfile to inform the compiler that you want to use another Swift version with this module.

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'MessageViewController'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

Hope this helps

**Comment by ashishfission** [comment]
@SD10  Thanks :)
